# Generated by Django 6.0.5 on 2026-05-14 09:24

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientprofile',
            name='age',
        ),
        migrations.RemoveField(
            model_name='driverprofile',
            name='age',
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='birth_date',
            field=models.DateField(default='2000-01-01', validators=[accounts.models.validate_adult]),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='birth_date',
            field=models.DateField(default='2000-01-01', validators=[accounts.models.validate_adult]),
        ),
    ]
