# Generated by Django 6.0.5 on 2026-05-14 09:25

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_clientprofile_age_remove_driverprofile_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='birth_date',
            field=models.DateField(validators=[accounts.models.validate_adult]),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='birth_date',
            field=models.DateField(validators=[accounts.models.validate_adult]),
        ),
    ]
